//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tv_Kanal_ModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sorumlu
    {
        public int SorumluID { get; set; }
        public string AdSoyad { get; set; }
        public string Görevli { get; set; }
        public decimal Maas { get; set; }
        public int GörevSayisi { get; set; }
        public int YayinID { get; set; }
    
        public virtual Yayin Yayin { get; set; }
    }
}
