//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tv_Kanal_ModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yayin
    {
        public Yayin()
        {
            this.Sorumlu = new HashSet<Sorumlu>();
        }
    
        public int YayinID { get; set; }
        public string YayinAdi { get; set; }
        public string YayinTarih { get; set; }
        public decimal Reyting { get; set; }
        public int KanalID { get; set; }
    
        public virtual Kanal Kanal { get; set; }
        public virtual ICollection<Sorumlu> Sorumlu { get; set; }
    }
}
